name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README
        run: |
          echo 'Algum texto ou dados dinâmicos' > README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README"
          git push
